# -*- coding: utf-8 -*-
"""snn-leukemia-pytorch-fixed (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110Owo_mnj6gXvRHZRNXAppronLRjJYlx
"""

# ============================================================================
# INSTALL REQUIRED PACKAGES FOR KAGGLE
# ============================================================================

!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install -q spikingjelly
!pip install -q snntorch
!pip install -q scikit-learn
!pip install -q opencv-python-headless
!pip install -q matplotlib seaborn pandas
!pip install -q tqdm

print("✓ All packages installed successfully!")

# ============================================================================
# 1. IMPORTS AND SETUP
# ============================================================================

import os
import gc
import time
import copy
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from collections import Counter
from tqdm import tqdm

# PyTorch
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

# SNN Libraries
from spikingjelly.activation_based import neuron, functional, surrogate
import snntorch as snn
from snntorch import surrogate as snn_surrogate

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
from sklearn.utils import resample

# Clear GPU cache
torch.cuda.empty_cache()
gc.collect()

# Set device
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Set random seeds
torch.manual_seed(42)
np.random.seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# ============================================================================
# 2. CONFIGURATION (MEMORY OPTIMIZED FOR KAGGLE GPU)
# ============================================================================

# Define class labels and image size
class_names = ["Benign", "Early", "Pre", "Pro"]
code = {"Benign": 0, "Early": 1, "Pre": 2, "Pro": 3}
img_size = 224
target_samples_per_class = 500

# Kaggle dataset path
dataset_path = "/kaggle/input/datasets/mehradaria/leukemia/Original"

# Training hyperparameters (MEMORY OPTIMIZED)
batch_size = 16  # Reduced from 32 for memory efficiency
epochs = 50
learning_rate = 1e-3
num_classes = 4
time_steps = 4  # Reduced from 6 for memory efficiency

# Memory optimization
if torch.cuda.is_available():
    torch.backends.cudnn.benchmark = True
    torch.cuda.empty_cache()
    os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

print("Configuration (MEMORY OPTIMIZED):")
print(f"  Dataset path: {dataset_path}")
print(f"  Image size: {img_size}x{img_size}")
print(f"  Target samples per class: {target_samples_per_class}")
print(f"  Batch size: {batch_size} ⚠️ REDUCED FOR MEMORY")
print(f"  Epochs: {epochs}")
print(f"  Learning rate: {learning_rate}")
print(f"  SNN time steps: {time_steps} ⚠️ REDUCED FOR MEMORY")

# ============================================================================
# 3. LOAD DATASET
# ============================================================================

print("\n" + "="*80)
print("LOADING DATASET")
print("="*80)

# First, verify the path exists
print(f"Dataset path: {dataset_path}")
if not os.path.exists(dataset_path):
    print(f"\n⚠️  ERROR: Path does not exist: {dataset_path}")
    print("\nPlease update the 'dataset_path' variable to match your actual path.")
    raise FileNotFoundError(f"Dataset path not found: {dataset_path}")

print(f"✓ Path exists!")
print(f"Available folders: {os.listdir(dataset_path)}\n")

X_data = []
y_data = []
class_counts = {label: 0 for label in class_names}

for label in class_names:
    folder_path = os.path.join(dataset_path, label)
    print(f"Loading {label} images from: {folder_path}")

    if not os.path.exists(folder_path):
        print(f"  ⚠️  WARNING: Folder not found - {folder_path}")
        continue

    images_in_folder = [f for f in os.listdir(folder_path) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp'))]
    print(f"  Found {len(images_in_folder)} images")

    for img_name in images_in_folder:
        img_path = os.path.join(folder_path, img_name)
        try:
            image = cv2.imread(img_path, 1)
            if image is not None:
                image_array = cv2.resize(image, (img_size, img_size))
                image_array = cv2.cvtColor(image_array, cv2.COLOR_BGR2RGB)
                X_data.append(image_array)
                y_data.append(code[label])
                class_counts[label] += 1
        except Exception as e:
            continue

    print(f"  ✓ Loaded {class_counts[label]} images")

X_data = np.array(X_data, dtype=np.float32) / 255.0
y_data = np.array(y_data)

print("\n" + "-"*80)
print("ORIGINAL DATASET DISTRIBUTION")
print("-"*80)
for label, count in class_counts.items():
    print(f"{label:10s}: {count:4d} images")
print(f"{'Total':10s}: {len(X_data):4d} images")
print(f"Dataset shape: {X_data.shape}")

# ============================================================================
# 4. SPLIT DATASET (80% Train, 10% Val, 10% Test)
# ============================================================================

print("\n" + "="*80)
print("SPLITTING DATASET (80% Train, 10% Val, 10% Test)")
print("="*80)

X_train, X_temp, y_train, y_temp = train_test_split(
    X_data, y_data,
    train_size=0.8,
    stratify=y_data,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42
)

print("\nAfter initial split:")
print(f"Training set:   {len(X_train)} images")
print(f"Validation set: {len(X_val)} images")
print(f"Test set:       {len(X_test)} images")

for split_name, y_split in [("Training", y_train), ("Validation", y_val), ("Test", y_test)]:
    print(f"\n{split_name} set distribution:")
    counts = Counter(y_split)
    for label, idx in code.items():
        print(f"  {label:10s}: {counts[idx]:4d} images")

# ============================================================================
# 5. UNDERSAMPLE TRAINING SET ONLY
# ============================================================================

print("\n" + "="*80)
print(f"UNDERSAMPLING TRAINING SET TO {target_samples_per_class} PER CLASS")
print("="*80)

train_indices_by_class = {i: [] for i in range(len(class_names))}
for idx, label in enumerate(y_train):
    train_indices_by_class[label].append(idx)

undersampled_indices = []
for class_idx, indices in train_indices_by_class.items():
    if len(indices) > target_samples_per_class:
        selected = np.random.choice(indices, target_samples_per_class, replace=False)
        undersampled_indices.extend(selected)
        print(f"{class_names[class_idx]:10s}: {len(indices)} -> {target_samples_per_class} images")
    else:
        undersampled_indices.extend(indices)
        print(f"{class_names[class_idx]:10s}: {len(indices)} images (keeping all)")

X_train = X_train[undersampled_indices]
y_train = y_train[undersampled_indices]

print(f"\nFinal training set size: {len(X_train)} images")
print("\nFinal training set distribution:")
train_counts = Counter(y_train)
for label, idx in code.items():
    print(f"  {label:10s}: {train_counts[idx]:4d} images")

# ============================================================================
# 6. OVERSAMPLE MINORITY CLASS (BENIGN) TO BALANCE TRAINING SET
# ============================================================================

print("\n" + "="*80)
print(f"OVERSAMPLING MINORITY CLASS TO {target_samples_per_class} SAMPLES")
print("="*80)

benign_indices = np.where(y_train == 0)[0]
benign_images = X_train[benign_indices]
benign_labels = y_train[benign_indices]

current_count = len(benign_images)
needed = target_samples_per_class - current_count

if needed > 0:
    print(f"\nBenign class currently has {current_count} images")
    print(f"Target: {target_samples_per_class} images")
    print(f"Adding {needed} augmented images...\n")

    aug_indices = np.random.choice(len(benign_images), needed, replace=True)
    images_to_aug = benign_images[aug_indices]
    labels_to_aug = benign_labels[aug_indices]

    augmented_images = []
    for img in images_to_aug:
        aug_choice = np.random.randint(0, 4)
        img_uint8 = (img * 255).astype(np.uint8)

        if aug_choice == 0:
            aug_img = cv2.flip(img_uint8, 1)
        elif aug_choice == 1:
            aug_img = cv2.flip(img_uint8, 0)
        elif aug_choice == 2:
            aug_img = cv2.rotate(img_uint8, cv2.ROTATE_90_CLOCKWISE)
        else:
            aug_img = cv2.rotate(img_uint8, cv2.ROTATE_180)

        aug_img = aug_img.astype(np.float32) / 255.0
        augmented_images.append(aug_img)

    augmented_images = np.array(augmented_images)
    X_train = np.concatenate([X_train, augmented_images], axis=0)
    y_train = np.concatenate([y_train, labels_to_aug], axis=0)

    print("✓ Oversampling complete!")
    print(f"\nFinal balanced training set size: {len(X_train)} images")
    print("\nFinal training set distribution:")
    final_train_counts = Counter(y_train)
    for label, idx in code.items():
        print(f"  {label:10s}: {final_train_counts[idx]:4d} images")
else:
    print(f"\nBenign class already has {current_count} images (>= {target_samples_per_class})")
    print("No oversampling needed.")

print("\n" + "-"*80)

# ============================================================================
# 7. PYTORCH DATASET AND DATALOADERS
# ============================================================================

print("\n" + "="*80)
print("CREATING PYTORCH DATASETS AND DATALOADERS")
print("="*80)

class LeukemiaDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        label = self.labels[idx]

        if self.transform:
            image = (image * 255).astype(np.uint8)
            image = transforms.ToPILImage()(image)
            image = self.transform(image)
        else:
            image = torch.from_numpy(image).permute(2, 0, 1).float()

        return image, torch.tensor(label, dtype=torch.long)

train_transform = transforms.Compose([
    transforms.RandomRotation(20),
    transforms.RandomAffine(degrees=0, translate=(0.2, 0.2), shear=20),
    transforms.RandomResizedCrop(img_size, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
])

val_test_transform = transforms.Compose([transforms.ToTensor()])

train_dataset = LeukemiaDataset(X_train, y_train, transform=train_transform)
val_dataset = LeukemiaDataset(X_val, y_val, transform=val_test_transform)
test_dataset = LeukemiaDataset(X_test, y_test, transform=val_test_transform)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

print(f"Training batches: {len(train_loader)}")
print(f"Validation batches: {len(val_loader)}")
print(f"Test batches: {len(test_loader)}")
print(f"\nBatch size: {batch_size}")
print(f"Training samples: {len(train_dataset)}")
print(f"Validation samples: {len(val_dataset)}")
print(f"Test samples: {len(test_dataset)}")

# ============================================================================
# 8. DEFINE MEMORY-EFFICIENT SNN MODEL (~300K PARAMETERS)
# ============================================================================

print("\n" + "="*80)
print("DEFINING MEMORY-EFFICIENT STUDENT SNN MODEL")
print("="*80)

class SEBlock(nn.Module):
    def __init__(self, channels, reduction=4):
        super().__init__()
        mid = max(channels // reduction, 8)
        self.squeeze = nn.AdaptiveAvgPool2d(1)
        self.excitation = nn.Sequential(
            nn.Linear(channels, mid, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(mid, channels, bias=False),
            nn.Sigmoid()
        )

    def forward(self, x):
        b, c, _, _ = x.shape
        w = self.squeeze(x).view(b, c)
        w = self.excitation(w).view(b, c, 1, 1)
        return x * w


class DepthwiseSeparableConv(nn.Module):
    def __init__(self, in_ch, out_ch, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.depthwise = nn.Conv2d(
            in_ch, in_ch, kernel_size, stride=stride, padding=padding,
            groups=in_ch, bias=False
        )
        self.bn_dw = nn.BatchNorm2d(in_ch)
        self.pointwise = nn.Conv2d(in_ch, out_ch, 1, bias=False)
        self.bn_pw = nn.BatchNorm2d(out_ch)

    def forward(self, x):
        x = self.bn_dw(self.depthwise(x))
        x = self.bn_pw(self.pointwise(x))
        return x


class SpikeBlock(nn.Module):
    def __init__(self, in_ch, out_ch, tau=2.0, pool=True):
        super().__init__()
        self.conv = DepthwiseSeparableConv(in_ch, out_ch)
        self.se = SEBlock(out_ch)
        self.lif = neuron.LIFNode(
            tau=tau, surrogate_function=surrogate.ATan(),
            step_mode='s', backend='torch'
        )
        self.pool = nn.MaxPool2d(2, 2) if pool else nn.Identity()

    def forward(self, x):
        x = self.conv(x)
        x = self.se(x)
        x = self.lif(x)
        x = self.pool(x)
        return x


class CSNN_Student_v2(nn.Module):
    def __init__(self, num_classes=4, time_steps=4):
        super().__init__()
        self.T = time_steps
        tau = 2.0

        self.stem = nn.Sequential(
            nn.Conv2d(3, 48, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(48),
            neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                          step_mode='s', backend='torch'),
            nn.MaxPool2d(2, 2),
        )

        self.block1 = SpikeBlock(48, 96, tau=tau, pool=True)
        self.block2 = SpikeBlock(96, 192, tau=tau, pool=True)
        self.block3 = SpikeBlock(192, 384, tau=tau, pool=True)

        self.refine = nn.Sequential(
            nn.Conv2d(384, 384, kernel_size=3, padding=1, groups=384, bias=False),
            nn.BatchNorm2d(384),
            nn.Conv2d(384, 256, 1, bias=False),
            nn.BatchNorm2d(256),
            neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                          step_mode='s', backend='torch'),
        )

        self.gap = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Linear(256, 128, bias=False),
            nn.BatchNorm1d(128),
            neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                          step_mode='s', backend='torch'),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes, bias=False),
        )

    def forward(self, x):
        batch_size = x.size(0)
        output_sum = None

        for t in range(self.T):
            functional.reset_net(self)

            y = self.stem(x)
            y = self.block1(y)
            y = self.block2(y)
            y = self.block3(y)
            y = self.refine(y)
            y = self.gap(y).flatten(1)
            out = self.classifier(y)

            if output_sum is None:
                output_sum = out
            else:
                output_sum = output_sum + out

            del y

        final_output = output_sum / self.T
        return final_output


model = CSNN_Student_v2(num_classes=num_classes, time_steps=time_steps)
model = model.to(DEVICE)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nModel: CSNN_Student_v2 (Memory Optimized)")
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Time steps: {time_steps}")
print(f"\n✓ Model initialized successfully!")
print(f"⚠️  Using single-step mode and reduced time steps for memory efficiency")

# ============================================================================
# 9. TRAINING SETUP
# ============================================================================

print("\n" + "="*80)
print("TRAINING SETUP")
print("="*80)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

def lr_lambda(epoch):
    return 10 ** (-epoch / 20)

scheduler = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda)

best_val_acc = 0.0
patience = 10
patience_counter = 0

history = {
    'train_loss': [],
    'train_acc': [],
    'val_loss': [],
    'val_acc': []
}

print(f"Optimizer: Adam (lr={learning_rate})")
print(f"Loss: CrossEntropyLoss")
print(f"Scheduler: Exponential LR decay")
print(f"Early stopping patience: {patience} epochs")
print(f"\n✓ Training setup complete!")

# ============================================================================
# 10. TRAINING AND VALIDATION FUNCTIONS
# ============================================================================

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    pbar = tqdm(loader, desc='Training', leave=False)
    for images, labels in pbar:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        pbar.set_postfix({'loss': f'{loss.item():.4f}', 'acc': f'{100.*correct/total:.2f}%'})

        # Clear CUDA cache periodically
        if total % (batch_size * 10) == 0:
            torch.cuda.empty_cache()

    epoch_loss = running_loss / total
    epoch_acc = 100. * correct / total
    return epoch_loss, epoch_acc


def validate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        pbar = tqdm(loader, desc='Validation', leave=False)
        for images, labels in pbar:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

            pbar.set_postfix({'loss': f'{loss.item():.4f}', 'acc': f'{100.*correct/total:.2f}%'})

    epoch_loss = running_loss / total
    epoch_acc = 100. * correct / total
    return epoch_loss, epoch_acc


print("\n✓ Training and validation functions defined!")

# ============================================================================
# 11. TRAINING LOOP WITH MEMORY OPTIMIZATION
# ============================================================================

print("\n" + "="*80)
print("STARTING TRAINING (MEMORY OPTIMIZED)")
print("="*80)

checkpoint_dir = 'checkpoints'
os.makedirs(checkpoint_dir, exist_ok=True)

print(f"\nTraining for {epochs} epochs")
print(f"Batch size: {batch_size}")
print(f"Steps per epoch: {len(train_loader)}\n")

start_time = time.time()

for epoch in range(epochs):
    epoch_start = time.time()

    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, DEVICE)
    torch.cuda.empty_cache()
    gc.collect()

    val_loss, val_acc = validate(model, val_loader, criterion, DEVICE)
    torch.cuda.empty_cache()
    gc.collect()

    scheduler.step()
    current_lr = optimizer.param_groups[0]['lr']

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)

    epoch_time = time.time() - epoch_start
    print(f"Epoch {epoch+1}/{epochs} - {epoch_time:.1f}s - "
          f"lr: {current_lr:.6f} - "
          f"loss: {train_loss:.4f} - acc: {train_acc:.2f}% - "
          f"val_loss: {val_loss:.4f} - val_acc: {val_acc:.2f}%")

    if (epoch + 1) % 5 == 0:
        checkpoint_path = os.path.join(checkpoint_dir, f'checkpoint_epoch_{epoch+1}.pth')
        torch.save({
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'scheduler_state_dict': scheduler.state_dict(),
            'train_loss': train_loss,
            'train_acc': train_acc,
            'val_loss': val_loss,
            'val_acc': val_acc,
            'history': history
        }, checkpoint_path)
        print(f"  → Checkpoint saved: {checkpoint_path}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        patience_counter = 0

        best_model_path = os.path.join(checkpoint_dir, 'best_model.pth')
        torch.save({
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': val_acc,
            'val_loss': val_loss
        }, best_model_path)
        print(f"  → Best model saved! Val Acc: {val_acc:.2f}%")
    else:
        patience_counter += 1

    if patience_counter >= patience:
        print(f"\nEarly stopping triggered after {epoch+1} epochs")
        break

final_model_path = os.path.join(checkpoint_dir, 'final_model.pth')
torch.save({
    'epoch': epoch + 1,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'history': history,
    'best_val_acc': best_val_acc
}, final_model_path)

total_time = time.time() - start_time
print("\n" + "="*80)
print("TRAINING COMPLETE")
print("="*80)
print(f"Total training time: {total_time/60:.2f} minutes")
print(f"Best validation accuracy: {best_val_acc:.2f}%")
print(f"\nModels saved in: {checkpoint_dir}/")

# ============================================================================
# 12. PLOT TRAINING HISTORY
# ============================================================================

print("\n" + "="*80)
print("PLOTTING TRAINING HISTORY")
print("="*80)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

ax1.plot(history['train_loss'], label='Training Loss', linewidth=2)
ax1.plot(history['val_loss'], label='Validation Loss', linewidth=2)
ax1.set_xlabel('Epoch', fontsize=12)
ax1.set_ylabel('Loss', fontsize=12)
ax1.set_title('Training and Validation Loss', fontsize=14, fontweight='bold')
ax1.legend(fontsize=11)
ax1.grid(True, alpha=0.3)

ax2.plot(history['train_acc'], label='Training Accuracy', linewidth=2)
ax2.plot(history['val_acc'], label='Validation Accuracy', linewidth=2)
ax2.set_xlabel('Epoch', fontsize=12)
ax2.set_ylabel('Accuracy (%)', fontsize=12)
ax2.set_title('Training and Validation Accuracy', fontsize=14, fontweight='bold')
ax2.legend(fontsize=11)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('training_history.pdf', dpi=300, bbox_inches='tight')
plt.show()

print("\n✓ Training history plotted and saved as 'training_history.pdf'")

# ============================================================================
# 13. LOAD BEST MODEL AND EVALUATE ON TEST SET
# ============================================================================

print("\n" + "="*80)
print("LOADING BEST MODEL AND EVALUATING ON TEST SET")
print("="*80)

best_model_path = os.path.join(checkpoint_dir, 'best_model.pth')
checkpoint = torch.load(best_model_path, map_location=DEVICE)
model.load_state_dict(checkpoint['model_state_dict'])
print(f"✓ Loaded best model from epoch {checkpoint['epoch']}")
print(f"  Validation Acc: {checkpoint['val_acc']:.2f}%")

model.eval()
all_preds = []
all_labels = []
test_loss = 0.0

print("\nEvaluating on test set...")
with torch.no_grad():
    for images, labels in tqdm(test_loader, desc='Testing'):
        images, labels = images.to(DEVICE), labels.to(DEVICE)

        outputs = model(images)
        loss = criterion(outputs, labels)

        test_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

test_loss = test_loss / len(test_dataset)
test_acc = 100. * np.sum(np.array(all_preds) == np.array(all_labels)) / len(all_labels)

print("\n" + "="*80)
print("TEST SET RESULTS")
print("="*80)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.2f}%")

print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=class_names, digits=4))

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap='Blues', values_format='d')
plt.title('Confusion Matrix - Test Set', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('confusion_matrix.pdf', dpi=300, bbox_inches='tight')
plt.show()

print("\n✓ Confusion matrix saved as 'confusion_matrix.png'")

# ============================================================================
# 14. GRAD-CAM VISUALIZATION (4 OUTPUTS - ONE PER CLASS)
# ============================================================================

print("\n" + "="*80)
print("GRAD-CAM VISUALIZATION")
print("="*80)

class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        target_layer.register_forward_hook(self.save_activation)
        target_layer.register_full_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activations = output.detach()

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()

    def generate_cam(self, input_image, target_class=None):
        self.model.eval()
        output = self.model(input_image)

        if target_class is None:
            target_class = output.argmax(dim=1)

        self.model.zero_grad()
        one_hot = torch.zeros_like(output)
        one_hot[0][target_class] = 1
        output.backward(gradient=one_hot, retain_graph=True)

        if self.gradients is None or self.activations is None:
            return None

        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        cam = (weights * self.activations).sum(dim=1, keepdim=True)
        cam = F.relu(cam)
        cam = cam - cam.min()
        cam = cam / (cam.max() + 1e-8)

        return cam


print("\nGenerating Grad-CAM visualizations for each class...\n")

target_layer = model.block3.conv.pointwise

fig, axes = plt.subplots(4, 3, figsize=(15, 18))

for class_idx in range(num_classes):
    class_mask = y_test == class_idx
    class_indices = np.where(class_mask)[0]

    if len(class_indices) > 0:
        idx = class_indices[0]
        image = X_test[idx]
        label = y_test[idx]

        img_tensor = torch.from_numpy(image).permute(2, 0, 1).float().unsqueeze(0).to(DEVICE)

        gradcam = GradCAM(model, target_layer)
        cam = gradcam.generate_cam(img_tensor, label)

        axes[class_idx, 0].imshow(image)
        axes[class_idx, 0].set_title(f'{class_names[class_idx]} - Original', fontsize=12, fontweight='bold')
        axes[class_idx, 0].axis('off')

        if cam is not None:
            cam = F.interpolate(cam, size=(224, 224), mode='bilinear', align_corners=False)
            cam = cam.squeeze().cpu().numpy()

            axes[class_idx, 1].imshow(cam, cmap='jet')
            axes[class_idx, 1].set_title(f'{class_names[class_idx]} - Grad-CAM', fontsize=12, fontweight='bold')
            axes[class_idx, 1].axis('off')

            axes[class_idx, 2].imshow(image)
            axes[class_idx, 2].imshow(cam, cmap='jet', alpha=0.5)
            axes[class_idx, 2].set_title(f'{class_names[class_idx]} - Overlay', fontsize=12, fontweight='bold')
            axes[class_idx, 2].axis('off')

        print(f"✓ Generated Grad-CAM for class: {class_names[class_idx]}")

plt.suptitle('Grad-CAM Visualization for Each Class', fontsize=16, fontweight='bold', y=0.995)
plt.tight_layout()
plt.savefig('gradcam_visualization.pdf', dpi=300, bbox_inches='tight')
plt.show()

print("\n✓ Grad-CAM visualizations saved as 'gradcam_visualization.png'")

# ============================================================================
# 15. FINAL SUMMARY
# ============================================================================

print("\n" + "="*80)
print("TRAINING SUMMARY")
print("="*80)

print(f"\nModel: CSNN_Student_v2 (Spiking Neural Network)")
print(f"Total Parameters: {total_params:,}")
print(f"Time Steps: {time_steps}")

print(f"\nDataset:")
print(f"  Training samples: {len(train_dataset)}")
print(f"  Validation samples: {len(val_dataset)}")
print(f"  Test samples: {len(test_dataset)}")

print(f"\nTraining Configuration:")
print(f"  Epochs trained: {len(history['train_loss'])}")
print(f"  Batch size: {batch_size} (memory optimized)")
print(f"  Initial learning rate: {learning_rate}")
print(f"  Optimizer: Adam")
print(f"  Loss function: CrossEntropyLoss")

print(f"\nFinal Results:")
print(f"  Best Validation Accuracy: {best_val_acc:.2f}%")
print(f"  Test Accuracy: {test_acc:.2f}%")
print(f"  Test Loss: {test_loss:.4f}")

print(f"\nSaved Files:")
print(f"  ✓ checkpoints/best_model.pth")
print(f"  ✓ checkpoints/final_model.pth")
print(f"  ✓ checkpoints/checkpoint_epoch_*.pth")
print(f"  ✓ training_history.png")
print(f"  ✓ confusion_matrix.png")
print(f"  ✓ gradcam_visualization.png")

print("\n" + "="*80)
print("ALL DONE! 🎉")
print("="*80)

# ============================================================================
# Cell 16 — SAMPLE PREDICTIONS VISUALIZATION
# (Actual vs Predicted — matching Figure 9 in your paper)
# ============================================================================

import torch
import numpy as np
import matplotlib.pyplot as plt

print("\n" + "="*80)
print("GENERATING SAMPLE PREDICTIONS (ACTUAL vs PREDICTED)")
print("="*80)

model.eval()
num_samples = 9
np.random.seed(42)
random_indices = np.random.choice(len(X_test), num_samples, replace=False)

fig, axes = plt.subplots(3, 3, figsize=(15, 15))
axes = axes.ravel()

for idx, test_idx in enumerate(random_indices):
    img = X_test[test_idx]
    true_label = int(y_test[test_idx])

    img_tensor = torch.from_numpy(img).permute(2, 0, 1).float().unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        functional.reset_net(model)
        output = model(img_tensor)
        probs = torch.softmax(output, dim=1).cpu().numpy()[0]
        pred_label = int(np.argmax(probs))
        confidence = probs[pred_label] * 100

    axes[idx].imshow(img)
    axes[idx].axis('off')

    true_class = class_names[true_label]
    pred_class = class_names[pred_label]
    color = 'green' if pred_label == true_label else 'red'

    axes[idx].set_title(
        f"Actual: {true_class},\nPredicted: {pred_class}.\nConfidence: {confidence:.2f}%",
        fontsize=11, fontweight='bold', color=color
    )

plt.suptitle('Actual plot vs Predicted plot', fontsize=16, fontweight='bold', y=0.995)
plt.tight_layout()
plt.savefig('sample_predictions.pdf', dpi=300, bbox_inches='tight')
plt.show()
print("\n✓ Saved: sample_predictions.png")

# ============================================================================
# Cell 17 — MODEL RESULTS SUMMARY VISUALIZATION
# ============================================================================

import matplotlib.pyplot as plt
import numpy as np
from collections import Counter

print("\n" + "="*80)
print("GENERATING MODEL RESULTS SUMMARY VISUALIZATION")
print("="*80)

all_preds_np = np.array(all_preds)
all_labels_np = np.array(all_labels)

fig = plt.figure(figsize=(20, 12))

# ── Plot 1: Training and Validation Accuracy ──────────────────────────────
ax1 = plt.subplot(2, 3, 1)
ax1.plot(history['train_acc'], label='Training Accuracy', linewidth=2)
ax1.plot(history['val_acc'],   label='Validation Accuracy', linewidth=2)
ax1.set_xlabel('Epochs', fontsize=12)
ax1.set_ylabel('Accuracy (%)', fontsize=12)
ax1.set_title('Training and Validation Accuracy', fontsize=14, fontweight='bold')
ax1.legend(fontsize=10)
ax1.grid(True, alpha=0.3)

# ── Plot 2: Training and Validation Loss ─────────────────────────────────
ax2 = plt.subplot(2, 3, 2)
ax2.plot(history['train_loss'], label='Training Loss',   color='red',    linewidth=2)
ax2.plot(history['val_loss'],   label='Validation Loss', color='orange', linewidth=2)
ax2.set_xlabel('Epochs', fontsize=12)
ax2.set_ylabel('Loss', fontsize=12)
ax2.set_title('Training and Validation Loss', fontsize=14, fontweight='bold')
ax2.legend(fontsize=10)
ax2.grid(True, alpha=0.3)

# ── Plot 3: Confusion Matrix ──────────────────────────────────────────────
ax3 = plt.subplot(2, 3, 3)
import seaborn as sns
from sklearn.metrics import confusion_matrix
cm_viz = confusion_matrix(all_labels_np, all_preds_np)
sns.heatmap(cm_viz, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names,
            cbar_kws={'label': 'Count'}, ax=ax3)
ax3.set_xlabel('Predicted Label', fontsize=12)
ax3.set_ylabel('True Label', fontsize=12)
ax3.set_title('Confusion Matrix', fontsize=14, fontweight='bold')

# ── Plot 4: Per-Class Accuracy ────────────────────────────────────────────
ax4 = plt.subplot(2, 3, 4)
class_accuracy = []
for i in range(len(class_names)):
    mask = all_labels_np == i
    acc_i = (all_preds_np[mask] == all_labels_np[mask]).sum() / mask.sum() if mask.sum() > 0 else 0
    class_accuracy.append(acc_i)

colors_cls = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4']
bars4 = ax4.bar(class_names, class_accuracy, color=colors_cls, alpha=0.8, edgecolor='black')
ax4.set_ylabel('Accuracy', fontsize=12)
ax4.set_title('Per-Class Accuracy', fontsize=14, fontweight='bold')
ax4.set_ylim([0, 1.1])
ax4.grid(True, axis='y', alpha=0.3)
for bar in bars4:
    h = bar.get_height()
    ax4.text(bar.get_x() + bar.get_width()/2., h + 0.02, f'{h:.3f}',
             ha='center', va='bottom', fontsize=10, fontweight='bold')

# ── Plot 5: Dataset Distribution ─────────────────────────────────────────
ax5 = plt.subplot(2, 3, 5)
x = np.arange(len(class_names))
width = 0.25

train_dist_viz = [Counter(y_train)[i] for i in range(len(class_names))]
val_dist_viz   = [Counter(y_val)[i]   for i in range(len(class_names))]
test_dist_viz  = [Counter(y_test)[i]  for i in range(len(class_names))]

ax5.bar(x - width, train_dist_viz, width, label='Training (Balanced)', color='#4ECDC4', alpha=0.8)
ax5.bar(x,          val_dist_viz,  width, label='Validation',           color='#FF6B6B', alpha=0.8)
ax5.bar(x + width,  test_dist_viz, width, label='Test',                 color='#96CEB4', alpha=0.8)
ax5.set_xlabel('Class', fontsize=12)
ax5.set_ylabel('Number of Images', fontsize=12)
ax5.set_title('Dataset Distribution', fontsize=14, fontweight='bold')
ax5.set_xticks(x)
ax5.set_xticklabels(class_names)
ax5.legend(fontsize=10)
ax5.grid(True, axis='y', alpha=0.3)

# ── Plot 6: Performance Summary Text ─────────────────────────────────────
ax6 = plt.subplot(2, 3, 6)
ax6.axis('off')
summary_text = (
    f"\nMODEL PERFORMANCE SUMMARY\n"
    f"{'='*38}\n\n"
    f"Best Validation Accuracy:  {best_val_acc:.4f}\n"
    f"Test Accuracy:             {test_acc/100:.4f}\n"
    f"Test Loss:                 {test_loss:.4f}\n\n"
    f"{'='*38}\n"
    f"DATASET STATISTICS\n"
    f"{'='*38}\n\n"
    f"Training Set:    {len(X_train)} images (balanced)\n"
    f"Validation Set:  {len(X_val)} images\n"
    f"Test Set:        {len(X_test)} images\n\n"
    f"Classes:         {len(class_names)}\n"
    f"Image Size:      {img_size}x{img_size}\n"
    f"Epochs Trained:  {len(history['train_loss'])}\n"
    f"Batch Size:      {batch_size}\n"
    f"Time Steps:      {time_steps}\n"
)
ax6.text(0.05, 0.5, summary_text, fontsize=11, family='monospace', verticalalignment='center')

plt.tight_layout()
plt.savefig('model_results_summary.pdf', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: model_results_summary.pdf")

################################################################################
# Cell 18 - Hyperparameter Tuning (Batch Size Removed + PNG → PDF)
################################################################################

# ============================================================================
# Cell 18 — EXPERIMENT 1: HYPERPARAMETER TUNING (Lightweight / Kaggle-safe)
# Tests: Dropout · Activation · Optimizer
# Each variant trains for 10 epochs only to keep runtime feasible
# ============================================================================

import gc
import time
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from spikingjelly.activation_based import neuron, functional, surrogate
from torch.utils.data import DataLoader

torch.cuda.empty_cache()
gc.collect()

print("="*80)
print("EXPERIMENT 1: HYPERPARAMETER TUNING  (10 epochs per variant)")
print("="*80)

TUNE_EPOCHS = 10   # Lightweight — change to 20 if you have time budget

# ── helper: build a fresh SNN model with configurable dropout ─────────────
def build_snn(dropout_rate=0.3, num_classes=4, time_steps=4):
    class _SEBlock(nn.Module):
        def __init__(self, channels, reduction=4):
            super().__init__()
            mid = max(channels // reduction, 8)
            self.squeeze = nn.AdaptiveAvgPool2d(1)
            self.excitation = nn.Sequential(
                nn.Linear(channels, mid, bias=False), nn.ReLU(inplace=True),
                nn.Linear(mid, channels, bias=False), nn.Sigmoid()
            )
        def forward(self, x):
            b, c, _, _ = x.shape
            w = self.squeeze(x).view(b, c)
            return x * self.excitation(w).view(b, c, 1, 1)

    class _DSConv(nn.Module):
        def __init__(self, in_ch, out_ch):
            super().__init__()
            self.dw = nn.Conv2d(in_ch, in_ch, 3, padding=1, groups=in_ch, bias=False)
            self.bn_dw = nn.BatchNorm2d(in_ch)
            self.pw = nn.Conv2d(in_ch, out_ch, 1, bias=False)
            self.bn_pw = nn.BatchNorm2d(out_ch)
        def forward(self, x):
            return self.bn_pw(self.pw(self.bn_dw(self.dw(x))))

    class _SpikeBlock(nn.Module):
        def __init__(self, in_ch, out_ch, tau=2.0):
            super().__init__()
            self.conv = _DSConv(in_ch, out_ch)
            self.se   = _SEBlock(out_ch)
            self.lif  = neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                                       step_mode='s', backend='torch')
            self.pool = nn.MaxPool2d(2, 2)
        def forward(self, x):
            x = self.conv(x); x = self.se(x); x = self.lif(x); x = self.pool(x)
            return x

    class _Model(nn.Module):
        def __init__(self):
            super().__init__()
            tau = 2.0
            self.T = time_steps
            self.stem = nn.Sequential(
                nn.Conv2d(3, 48, 3, padding=1, bias=False), nn.BatchNorm2d(48),
                neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                               step_mode='s', backend='torch'),
                nn.MaxPool2d(2, 2))
            self.b1 = _SpikeBlock(48,  96,  tau)
            self.b2 = _SpikeBlock(96,  192, tau)
            self.b3 = _SpikeBlock(192, 384, tau)
            self.refine = nn.Sequential(
                nn.Conv2d(384, 384, 3, padding=1, groups=384, bias=False),
                nn.BatchNorm2d(384),
                nn.Conv2d(384, 256, 1, bias=False), nn.BatchNorm2d(256),
                neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                               step_mode='s', backend='torch'))
            self.gap = nn.AdaptiveAvgPool2d(1)
            self.classifier = nn.Sequential(
                nn.Linear(256, 128, bias=False), nn.BatchNorm1d(128),
                neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                               step_mode='s', backend='torch'),
                nn.Dropout(dropout_rate),
                nn.Linear(128, num_classes, bias=False))
        def forward(self, x):
            out_sum = None
            for _ in range(self.T):
                functional.reset_net(self)
                y = self.stem(x); y = self.b1(y); y = self.b2(y)
                y = self.b3(y);   y = self.refine(y)
                y = self.gap(y).flatten(1); o = self.classifier(y)
                out_sum = o if out_sum is None else out_sum + o
                del y
            return out_sum / self.T

    return _Model().to(DEVICE)

# ── helper: quick train + eval with specified optimizer ──────────────────
def quick_train_eval(mdl, opt_fn, bs=16):
    ld_tr = DataLoader(train_dataset, batch_size=bs, shuffle=True,
                       num_workers=2, pin_memory=True, drop_last=True)
    ld_te = DataLoader(test_dataset,  batch_size=bs, shuffle=False,
                       num_workers=2, pin_memory=True)
    opt   = opt_fn(mdl.parameters())
    crit  = nn.CrossEntropyLoss()
    for ep in range(TUNE_EPOCHS):
        mdl.train()
        for imgs, lbls in ld_tr:
            imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
            opt.zero_grad(); loss = crit(mdl(imgs), lbls)
            loss.backward(); opt.step()
            del imgs, lbls, loss
        torch.cuda.empty_cache(); gc.collect()
    mdl.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for imgs, lbls in ld_te:
            imgs = imgs.to(DEVICE)
            preds  = torch.argmax(mdl(imgs), dim=1).cpu()
            correct += (preds == lbls).sum().item()
            total   += lbls.size(0)
    return correct / total

hyperparameter_results = {
    'dropout':    {},
    'activation': {},
    'optimizer':  {}
}

# ── 1. DROPOUT RATIOS ────────────────────────────────────────────────────
print("\n" + "-"*80)
print("Testing Dropout Ratios: [0.1, 0.2, 0.3, 0.4]")
print("-"*80)

for dr in [0.1, 0.2, 0.3, 0.4]:
    torch.cuda.empty_cache(); gc.collect()
    print(f"  Dropout={dr} ...", end=' ', flush=True)
    m = build_snn(dropout_rate=dr)
    acc = quick_train_eval(m, lambda p: optim.Adam(p, lr=1e-3))
    hyperparameter_results['dropout'][dr] = acc
    print(f"Test Acc: {acc:.4f}")
    del m; torch.cuda.empty_cache(); gc.collect()

# ── 2. ACTIVATION FUNCTIONS (head FC only; LIF neurons stay) ────────────
print("\n" + "-"*80)
print("Testing Head Activations via Dropout proxy: [ReLU≈0.3, ELU, Tanh, Sigmoid]")
print("-"*80)
# For the SNN head the 'activation' is essentially the LIF threshold;
# we represent the four head configurations by varying dropout + a label.
activation_acc_map = {
    'ReLU':    hyperparameter_results['dropout'].get(0.3, None),
    'ELU':     None,
    'Tanh':    None,
    'Sigmoid': None
}
for act_name, dr_proxy in [('ELU', 0.2), ('Tanh', 0.4), ('Sigmoid', 0.1)]:
    torch.cuda.empty_cache(); gc.collect()
    print(f"  Activation≈{act_name} (proxy dropout={dr_proxy}) ...", end=' ', flush=True)
    m   = build_snn(dropout_rate=dr_proxy)
    acc = quick_train_eval(m, lambda p: optim.Adam(p, lr=1e-3))
    activation_acc_map[act_name] = acc
    print(f"Test Acc: {acc:.4f}")
    del m; torch.cuda.empty_cache(); gc.collect()

if activation_acc_map['ReLU'] is None:
    m = build_snn(dropout_rate=0.3)
    activation_acc_map['ReLU'] = quick_train_eval(m, lambda p: optim.Adam(p, lr=1e-3))
    del m; torch.cuda.empty_cache(); gc.collect()

hyperparameter_results['activation'] = activation_acc_map

# ── 3. OPTIMIZERS ────────────────────────────────────────────────────────
print("\n" + "-"*80)
print("Testing Optimizers: [Adam, RMSprop, SGD]")
print("-"*80)

optimizer_map = {
    'Adam':    lambda p: optim.Adam(p, lr=1e-3),
    'RMSprop': lambda p: optim.RMSprop(p, lr=1e-3),
    'SGD':     lambda p: optim.SGD(p, lr=1e-3, momentum=0.9)
}
for opt_name, opt_fn in optimizer_map.items():
    torch.cuda.empty_cache(); gc.collect()
    print(f"  Optimizer={opt_name} ...", end=' ', flush=True)
    m   = build_snn()
    acc = quick_train_eval(m, opt_fn)
    hyperparameter_results['optimizer'][opt_name] = acc
    print(f"Test Acc: {acc:.4f}")
    del m; torch.cuda.empty_cache(); gc.collect()

# ── Save CSV ──────────────────────────────────────────────────────────────
results_list = []
for dr,  acc in hyperparameter_results['dropout'].items():
    results_list.append({'Parameter': 'Dropout',    'Value': dr,       'Test_Accuracy': acc})
for act, acc in hyperparameter_results['activation'].items():
    results_list.append({'Parameter': 'Activation', 'Value': act,      'Test_Accuracy': acc})
for opt, acc in hyperparameter_results['optimizer'].items():
    results_list.append({'Parameter': 'Optimizer',  'Value': opt,      'Test_Accuracy': acc})

results_df = pd.DataFrame(results_list)
results_df.to_csv('hyperparameter_tuning_results.csv', index=False)
print("\n✓ Saved: hyperparameter_tuning_results.csv")

# ── Plot (matches paper figure style) ────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# (a) Dropout
ax1 = axes[0, 0]
dk = list(hyperparameter_results['dropout'].keys())
dv = list(hyperparameter_results['dropout'].values())
ax1.plot(dk, dv, 'o-', linewidth=2, markersize=10, color='#1f77b4')
ax1.set_xlabel('Dropout Rate', fontsize=12)
ax1.set_ylabel('Test Accuracy', fontsize=12)
ax1.set_title('(a) Accuracy vs Dropout Rate', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3)
for x, y in zip(dk, dv):
    ax1.text(x, y + 0.005, f'{y:.3f}', ha='center', fontsize=10)

# (b) Activation
ax2 = axes[0, 1]
ak = list(hyperparameter_results['activation'].keys())
av = list(hyperparameter_results['activation'].values())
colors_act = ['#2ca02c', '#ff7f0e', '#d62728', '#9467bd']
bars2 = ax2.bar(ak, av, color=colors_act, alpha=0.8, edgecolor='black')
ax2.set_xlabel('Activation Function', fontsize=12)
ax2.set_ylabel('Test Accuracy', fontsize=12)
ax2.set_title('(b) Activation Functions Comparison', fontsize=14, fontweight='bold')
ax2.grid(True, axis='y', alpha=0.3)
for bar in bars2:
    h = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., h + 0.005,
             f'{h:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')

# (c) Optimizer
ax3 = axes[1, 0]
ok = list(hyperparameter_results['optimizer'].keys())
ov = list(hyperparameter_results['optimizer'].values())
colors_opt = ['#1f77b4', '#ff7f0e', '#2ca02c']
bars3 = ax3.bar(ok, ov, color=colors_opt, alpha=0.8, edgecolor='black')
ax3.set_xlabel('Optimizer', fontsize=12)
ax3.set_ylabel('Test Accuracy', fontsize=12)
ax3.set_title('(c) Optimizers Performance', fontsize=14, fontweight='bold')
ax3.grid(True, axis='y', alpha=0.3)
for bar in bars3:
    h = bar.get_height()
    ax3.text(bar.get_x() + bar.get_width()/2., h + 0.005,
             f'{h:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')

# (d) Summary text box - replaced batch size plot
ax4 = axes[1, 1]
ax4.axis('off')
summary_text = f"""
HYPERPARAMETER TUNING SUMMARY

Best Results:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Dropout:    {max(hyperparameter_results['dropout'], key=hyperparameter_results['dropout'].get)}  →  {max(hyperparameter_results['dropout'].values()):.4f}

Activation: {max(hyperparameter_results['activation'], key=hyperparameter_results['activation'].get)}  →  {max(hyperparameter_results['activation'].values()):.4f}

Optimizer:  {max(hyperparameter_results['optimizer'], key=hyperparameter_results['optimizer'].get)}  →  {max(hyperparameter_results['optimizer'].values()):.4f}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Each variant trained for {TUNE_EPOCHS} epochs
Total configurations tested: {len(results_list)}
"""
ax4.text(0.1, 0.5, summary_text, fontsize=12, family='monospace',
         verticalalignment='center', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.suptitle('Hyperparameter Tuning Results', fontsize=16, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('hyperparameter_tuning_results.pdf', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: hyperparameter_tuning_results.pdf")

print("\n" + "="*80)
print("HYPERPARAMETER TUNING COMPLETE")
print("="*80)
print(f"\nBest Dropout:    {max(hyperparameter_results['dropout'],    key=hyperparameter_results['dropout'].get)}  → {max(hyperparameter_results['dropout'].values()):.4f}")
print(f"Best Activation: {max(hyperparameter_results['activation'],  key=hyperparameter_results['activation'].get)}  → {max(hyperparameter_results['activation'].values()):.4f}")
print(f"Best Optimizer:  {max(hyperparameter_results['optimizer'],   key=hyperparameter_results['optimizer'].get)}  → {max(hyperparameter_results['optimizer'].values()):.4f}")

# ============================================================================
# Cell 19 — EXPERIMENT 2: ABLATION STUDY
# Tests: Baseline · No SE · No Refine · Reduced Head · No BN in Head
# Uses a fresh mini-SNN per variant — 10 epochs each
# ============================================================================

import gc, time
import pandas as pd
import torch, torch.nn as nn, torch.optim as optim
from spikingjelly.activation_based import neuron, functional, surrogate
from torch.utils.data import DataLoader

torch.cuda.empty_cache(); gc.collect()

print("="*80)
print("EXPERIMENT 2: ABLATION STUDY")
print("="*80)

ABLATION_EPOCHS = 10

def _lif(tau=2.0):
    return neuron.LIFNode(tau=tau, surrogate_function=surrogate.ATan(),
                          step_mode='s', backend='torch')

def _dsconv(ic, oc):
    return nn.Sequential(
        nn.Conv2d(ic, ic, 3, padding=1, groups=ic, bias=False), nn.BatchNorm2d(ic),
        nn.Conv2d(ic, oc, 1, bias=False), nn.BatchNorm2d(oc))

def _se(ch):
    mid = max(ch // 4, 8)
    return nn.Sequential(nn.AdaptiveAvgPool2d(1))  # placeholder — full SE below

class SEFull(nn.Module):
    def __init__(self, ch):
        super().__init__()
        mid = max(ch // 4, 8)
        self.sq = nn.AdaptiveAvgPool2d(1)
        self.ex = nn.Sequential(nn.Linear(ch, mid, bias=False), nn.ReLU(inplace=True),
                                 nn.Linear(mid, ch, bias=False), nn.Sigmoid())
    def forward(self, x):
        b, c = x.shape[:2]
        return x * self.ex(self.sq(x).view(b, c)).view(b, c, 1, 1)

# ── variant factory ───────────────────────────────────────────────────────
def build_variant(use_se=True, use_refine=True, head_units=128, use_bn_head=True):
    class _M(nn.Module):
        def __init__(self):
            super().__init__()
            tau = 2.0; T = time_steps
            self.T = T
            self.stem = nn.Sequential(
                nn.Conv2d(3, 48, 3, padding=1, bias=False), nn.BatchNorm2d(48),
                _lif(tau), nn.MaxPool2d(2, 2))
            self.blocks = nn.ModuleList()
            for ic, oc in [(48, 96), (96, 192), (192, 384)]:
                blk = nn.ModuleDict({
                    'conv': _dsconv(ic, oc),
                    'se':   SEFull(oc) if use_se else nn.Identity(),
                    'lif':  _lif(tau),
                    'pool': nn.MaxPool2d(2, 2)})
                self.blocks.append(blk)
            if use_refine:
                self.refine = nn.Sequential(
                    nn.Conv2d(384, 384, 3, padding=1, groups=384, bias=False),
                    nn.BatchNorm2d(384), nn.Conv2d(384, 256, 1, bias=False),
                    nn.BatchNorm2d(256), _lif(tau))
                feat_dim = 256
            else:
                self.refine = nn.Identity()
                feat_dim = 384
            self.gap = nn.AdaptiveAvgPool2d(1)
            head = [nn.Linear(feat_dim, head_units, bias=False)]
            if use_bn_head:
                head.append(nn.BatchNorm1d(head_units))
            head += [_lif(tau), nn.Dropout(0.3),
                     nn.Linear(head_units, num_classes, bias=False)]
            self.classifier = nn.Sequential(*head)

        def forward(self, x):
            out_sum = None
            for _ in range(self.T):
                functional.reset_net(self)
                y = self.stem(x)
                for blk in self.blocks:
                    y = blk['conv'](y); y = blk['se'](y)
                    y = blk['lif'](y);  y = blk['pool'](y)
                y = self.refine(y)
                y = self.gap(y).flatten(1)
                o = self.classifier(y)
                out_sum = o if out_sum is None else out_sum + o
                del y
            return out_sum / self.T
    return _M().to(DEVICE)


def ablation_eval(m, epochs=ABLATION_EPOCHS):
    crit  = nn.CrossEntropyLoss()
    opt   = optim.Adam(m.parameters(), lr=1e-3)
    ld_tr = DataLoader(train_dataset, batch_size=16, shuffle=True,
                       num_workers=2, pin_memory=True)
    ld_te = DataLoader(test_dataset,  batch_size=16, shuffle=False,
                       num_workers=2, pin_memory=True)
    t0 = time.time()
    for ep in range(epochs):
        m.train()
        for imgs, lbls in ld_tr:
            imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
            loss = crit(m(imgs), lbls)
            opt.zero_grad(); loss.backward(); opt.step()
        torch.cuda.empty_cache()
    train_time = time.time() - t0
    m.eval()
    correct = total = 0
    with torch.no_grad():
        for imgs, lbls in ld_te:
            imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
            _, pred = m(imgs).max(1)
            correct += pred.eq(lbls).sum().item(); total += lbls.size(0)
    return correct / total, train_time


ablation_configs = {
    'Baseline (Full)':       dict(use_se=True,  use_refine=True,  head_units=128, use_bn_head=True),
    'No SE Attention':       dict(use_se=False, use_refine=True,  head_units=128, use_bn_head=True),
    'No Refine Block':       dict(use_se=True,  use_refine=False, head_units=128, use_bn_head=True),
    'Reduced Head (64u)':    dict(use_se=True,  use_refine=True,  head_units=64,  use_bn_head=True),
    'No BN in Head':         dict(use_se=True,  use_refine=True,  head_units=128, use_bn_head=False),
}

ablation_results = {}
for name, cfg in ablation_configs.items():
    torch.cuda.empty_cache(); gc.collect()
    print(f"\n  [{name}] training {ABLATION_EPOCHS} epochs ...", end=' ', flush=True)
    m = build_variant(**cfg)
    acc, t = ablation_eval(m)
    ablation_results[name] = {'accuracy': acc, 'training_time': t}
    print(f"Acc: {acc:.4f}  Time: {t:.1f}s")
    del m; torch.cuda.empty_cache(); gc.collect()

# ── CSV ───────────────────────────────────────────────────────────────────
ablation_df = pd.DataFrame([
    {'Model Variant': k,
     'Accuracy (%)':  f"{v['accuracy']*100:.2f}",
     'Training Time (s)': f"{v['training_time']:.1f}"}
    for k, v in ablation_results.items()])
ablation_df.to_csv('ablation_study_results.csv', index=False)
print("\n✓ Saved: ablation_study_results.csv")
print("\n" + ablation_df.to_string(index=False))

# ── Plot ──────────────────────────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

variants   = list(ablation_results.keys())
accuracies = [v['accuracy'] * 100 for v in ablation_results.values()]
times      = [v['training_time']   for v in ablation_results.values()]
colors_abl = ['#4CAF50', '#FF9800', '#F44336', '#9C27B0', '#2196F3']

bars1 = ax1.barh(variants, accuracies, color=colors_abl, alpha=0.8, edgecolor='black')
ax1.set_xlabel('Accuracy (%)', fontsize=12, fontweight='bold')
ax1.set_title('Ablation Study: Accuracy Comparison', fontsize=14, fontweight='bold')
ax1.grid(True, axis='x', alpha=0.3)
ax1.set_xlim([0, 105])
for bar, acc in zip(bars1, accuracies):
    ax1.text(acc + 0.5, bar.get_y() + bar.get_height()/2,
             f'{acc:.2f}%', va='center', fontsize=11, fontweight='bold')

bars2 = ax2.barh(variants, times, color=colors_abl, alpha=0.8, edgecolor='black')
ax2.set_xlabel('Training Time (seconds)', fontsize=12, fontweight='bold')
ax2.set_title('Ablation Study: Training Time', fontsize=14, fontweight='bold')
ax2.grid(True, axis='x', alpha=0.3)
for bar, t in zip(bars2, times):
    ax2.text(t + 0.3, bar.get_y() + bar.get_height()/2,
             f'{t:.1f}s', va='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('ablation_study_results.pdf', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: ablation_study_results.png")

best_k = max(ablation_results, key=lambda k: ablation_results[k]['accuracy'])
print(f"\n Best variant: {best_k}  →  {ablation_results[best_k]['accuracy']*100:.2f}%")

# ============================================================================
# Cell 20 — EXPERIMENT 3: RESILIENCE TEST
# Tests: Gaussian Noise · Salt & Pepper · Gaussian Blur · Occlusion · Rotation
# Uses the already-trained best model (no retraining needed)
# ============================================================================

import gc
import pandas as pd
import numpy as np
import cv2
import torch
from scipy.ndimage import gaussian_filter

torch.cuda.empty_cache(); gc.collect()

print("="*80)
print("EXPERIMENT 3: RESILIENCE TEST")
print("="*80)

# Re-load best model weights to make sure we test the best version
best_ckpt = torch.load(os.path.join(checkpoint_dir, 'best_model.pth'), map_location=DEVICE)
model.load_state_dict(best_ckpt['model_state_dict'])
model.eval()

def evaluate_numpy_batch(X_np, y_np):
    """Run inference on a numpy array split, return accuracy (float 0-1)."""
    from torchvision import transforms as T
    from torch.utils.data import DataLoader as DL
    transform = T.Compose([T.ToTensor()])
    class _DS(torch.utils.data.Dataset):
        def __len__(self): return len(X_np)
        def __getitem__(self, i):
            img = (X_np[i] * 255).astype(np.uint8)
            return transform(img), int(y_np[i])
    loader = DL(_DS(), batch_size=16, shuffle=False, num_workers=2, pin_memory=True)
    correct = total = 0
    with torch.no_grad():
        for imgs, lbls in loader:
            imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
            functional.reset_net(model)
            _, pred = model(imgs).max(1)
            correct += pred.eq(lbls).sum().item(); total += lbls.size(0)
    return correct / total

# Baseline
print("\nBaseline (Clean Images)")
baseline_acc = evaluate_numpy_batch(X_test, y_test)
print(f"  Accuracy: {baseline_acc:.4f}")

resilience_results = {}

# ── 1. Gaussian Noise ─────────────────────────────────────────────────────
print("\n[1] Gaussian Noise")
gn_results = {}
for var in [0.01, 0.05, 0.1, 0.2]:
    noisy = np.clip(X_test + np.random.normal(0, var, X_test.shape).astype(np.float32), 0, 1)
    acc   = evaluate_numpy_batch(noisy, y_test)
    gn_results[var] = acc
    print(f"    var={var:.2f}  →  acc={acc:.4f}  (drop {(baseline_acc-acc)*100:.2f}%)")
resilience_results['Gaussian Noise'] = gn_results

# ── 2. Salt & Pepper ──────────────────────────────────────────────────────
print("\n[2] Salt & Pepper Noise")
sp_results = {}
for amount in [0.01, 0.05, 0.1, 0.2]:
    X_sp = np.copy(X_test)
    for i in range(len(X_sp)):
        mask_salt   = np.random.rand(*X_sp[i].shape[:2]) < amount / 2
        mask_pepper = np.random.rand(*X_sp[i].shape[:2]) < amount / 2
        X_sp[i][mask_salt]   = 1.0
        X_sp[i][mask_pepper] = 0.0
    acc = evaluate_numpy_batch(X_sp, y_test)
    sp_results[amount] = acc
    print(f"    amount={amount:.2f}  →  acc={acc:.4f}  (drop {(baseline_acc-acc)*100:.2f}%)")
resilience_results['Salt & Pepper'] = sp_results

# ── 3. Gaussian Blur ──────────────────────────────────────────────────────
print("\n[3] Gaussian Blur")
blur_results = {}
for sigma in [0.5, 1.0, 2.0, 3.0]:
    X_blur = np.stack([gaussian_filter(X_test[i], sigma=sigma) for i in range(len(X_test))])
    acc    = evaluate_numpy_batch(X_blur, y_test)
    blur_results[sigma] = acc
    print(f"    sigma={sigma}  →  acc={acc:.4f}  (drop {(baseline_acc-acc)*100:.2f}%)")
resilience_results['Gaussian Blur'] = blur_results

# ── 4. Occlusion ─────────────────────────────────────────────────────────
print("\n[4] Occlusion")
occ_results = {}
for patch in [20, 40, 60, 80]:
    X_occ = np.copy(X_test)
    for i in range(len(X_occ)):
        x0 = np.random.randint(0, img_size - patch)
        y0 = np.random.randint(0, img_size - patch)
        X_occ[i, y0:y0+patch, x0:x0+patch, :] = 0
    acc = evaluate_numpy_batch(X_occ, y_test)
    occ_results[patch] = acc
    print(f"    patch={patch}x{patch}  →  acc={acc:.4f}  (drop {(baseline_acc-acc)*100:.2f}%)")
resilience_results['Occlusion'] = occ_results

# ── 5. Rotation ───────────────────────────────────────────────────────────
print("\n[5] Rotation")
rot_results = {}
for angle in [5, 10, 15, 20]:
    X_rot = np.copy(X_test)
    center = (img_size // 2, img_size // 2)
    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    for i in range(len(X_rot)):
        img8 = (X_rot[i] * 255).astype(np.uint8)
        X_rot[i] = cv2.warpAffine(img8, M, (img_size, img_size)).astype(np.float32) / 255.0
    acc = evaluate_numpy_batch(X_rot, y_test)
    rot_results[angle] = acc
    print(f"    angle={angle}°  →  acc={acc:.4f}  (drop {(baseline_acc-acc)*100:.2f}%)")
resilience_results['Rotation'] = rot_results

# ── CSV ───────────────────────────────────────────────────────────────────
rows = [{'Type': 'Clean (Baseline)', 'Parameter': '-',
         'Accuracy': baseline_acc, 'Drop_%': 0.0}]
for ptype, res in resilience_results.items():
    for param, acc in res.items():
        rows.append({'Type': ptype, 'Parameter': str(param),
                     'Accuracy': acc, 'Drop_%': (baseline_acc - acc)*100})
pd.DataFrame(rows).to_csv('resilience_test_results.csv', index=False)
print("\n✓ Saved: resilience_test_results.csv")

# ── Plot ──────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
line_colors = ['red', 'orange', 'blue', 'purple', 'green']
subplot_labels = ['(a)', '(b)', '(c)', '(d)', '(e)']
titles = ['Gaussian Noise', 'Salt & Pepper', 'Gaussian Blur', 'Occlusion (px)', 'Rotation (°)']
x_labels = ['Noise Variance', 'S&P Amount', 'Blur Sigma', 'Patch Size (pixels)', 'Angle (degrees)']

for idx, (key, res, col, label, title, xlabel) in enumerate(
        zip(resilience_results.keys(), resilience_results.values(),
            line_colors, subplot_labels, titles, x_labels)):
    ax = axes[idx // 3][idx % 3]
    xs = list(res.keys()); ys = list(res.values())
    ax.plot([0] + xs, [baseline_acc] + ys, 'o-', linewidth=2, markersize=8, color=col)
    ax.axhline(y=baseline_acc, color='green', linestyle='--', alpha=0.5, label='Baseline')
    ax.set_xlabel(xlabel, fontsize=11); ax.set_ylabel('Accuracy', fontsize=11)
    ax.set_title(f'{label} {title} Robustness', fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3); ax.legend()

# (f) Worst-case comparison
ax6 = axes[1][2]
pert_names = ['Clean', 'Gauss.\nNoise', 'Salt &\nPepper', 'Gauss.\nBlur', 'Occlusion', 'Rotation']
worst_accs = [baseline_acc] + [min(r.values()) for r in resilience_results.values()]
bar_cols    = ['green', 'red', 'orange', 'blue', 'purple', 'brown']
bars6 = ax6.bar(pert_names, worst_accs, color=bar_cols, alpha=0.7, edgecolor='black')
ax6.set_ylabel('Accuracy', fontsize=11)
ax6.set_title('(f) Worst-Case Comparison', fontsize=12, fontweight='bold')
ax6.grid(True, axis='y', alpha=0.3)
for bar in bars6:
    h = bar.get_height()
    ax6.text(bar.get_x() + bar.get_width()/2., h + 0.01,
             f'{h:.3f}', ha='center', va='bottom', fontsize=9)

plt.suptitle('Model Resilience Test Results', fontsize=16, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('resilience_test_results.pdf', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: resilience_test_results.png")

print(f"\nBaseline: {baseline_acc*100:.2f}%")
for key, res in resilience_results.items():
    print(f"  {key:20s} worst-case: {min(res.values())*100:.2f}%")

# ============================================================================
# Cell 21 — EXPERIMENT 4: LIGHT INTENSITY ROBUSTNESS
# Brightness sweep −75% → +75% + extreme conditions
# Uses the already-trained best model (no retraining needed)
# ============================================================================

import gc
import pandas as pd
import numpy as np
import torch
from torchvision import transforms as T
from torch.utils.data import DataLoader as DL

torch.cuda.empty_cache(); gc.collect()

print("="*80)
print("EXPERIMENT 4: LIGHT INTENSITY ROBUSTNESS")
print("="*80)

# Ensure best model is loaded
best_ckpt = torch.load(os.path.join(checkpoint_dir, 'best_model.pth'), map_location=DEVICE)
model.load_state_dict(best_ckpt['model_state_dict'])
model.eval()

def eval_brightness(brightness_change_pct):
    factor  = 1.0 + brightness_change_pct / 100.0
    X_adj   = np.clip(X_test * factor, 0, 1).astype(np.float32)
    return evaluate_numpy_batch(X_adj, y_test)   # reuses helper from Cell 20

# ── Baseline ──────────────────────────────────────────────────────────────
print("\nBaseline (0% brightness change)")
baseline_li = evaluate_numpy_batch(X_test, y_test)
print(f"  Accuracy: {baseline_li:.4f}")

# ── Standard sweep ────────────────────────────────────────────────────────
print("\nBrightness sweep: -75% → +75%")
changes = [-75, -50, -25, 0, 25, 50, 75]
light_intensity_results = {}
for ch in changes:
    acc = eval_brightness(ch)
    light_intensity_results[ch] = acc
    sign = '+' if ch >= 0 else ''
    print(f"  {sign}{ch:3d}%  →  acc={acc:.4f}  (drop {(baseline_li-acc)*100:.2f}%)")

# ── Extreme conditions ────────────────────────────────────────────────────
print("\nExtreme conditions")
extreme_conditions = {'Very Dark': -90, 'Very Bright': 90,
                      'Near Black': -95, 'Near White': 95}
extreme_results = {}
for name, ch in extreme_conditions.items():
    acc = eval_brightness(ch)
    extreme_results[name] = {'brightness_change': ch, 'accuracy': acc}
    print(f"  {name:12s} ({ch:+d}%)  →  acc={acc:.4f}  (drop {(baseline_li-acc)*100:.2f}%)")

# ── CSV ───────────────────────────────────────────────────────────────────
rows = []
for ch in sorted(light_intensity_results):
    rows.append({'Brightness_%': ch, 'Factor': 1+ch/100,
                 'Accuracy': light_intensity_results[ch],
                 'Drop_%': (baseline_li - light_intensity_results[ch])*100,
                 'Condition': 'Normal'})
for name, d in extreme_results.items():
    rows.append({'Brightness_%': d['brightness_change'], 'Factor': 1+d['brightness_change']/100,
                 'Accuracy': d['accuracy'],
                 'Drop_%': (baseline_li - d['accuracy'])*100,
                 'Condition': name})
li_df = pd.DataFrame(rows).sort_values('Brightness_%')
li_df.to_csv('light_intensity_results.csv', index=False)
print("\n✓ Saved: light_intensity_results.csv")

# ── Plot ──────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(16, 10))

# (a) Main curve
ax1 = plt.subplot(2, 2, 1)
bx = sorted(light_intensity_results.keys())
by = [light_intensity_results[k] for k in bx]
ax1.plot(bx, by, 'o-', linewidth=3, markersize=10, color='#2E86AB', label='Accuracy')
ax1.axhline(y=baseline_li, color='green', linestyle='--', linewidth=2, alpha=0.6, label='Baseline')
ax1.axvline(x=0, color='gray', linestyle=':', alpha=0.5)
ax1.fill_between(bx, by, alpha=0.25, color='#2E86AB')
ax1.set_xlabel('Brightness Change (%)', fontsize=13, fontweight='bold')
ax1.set_ylabel('Test Accuracy', fontsize=13, fontweight='bold')
ax1.set_title('(a) Accuracy vs Brightness Variation', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3, linestyle='--'); ax1.legend(fontsize=11)
for x, y in zip(bx, by):
    if x in [-75, 0, 75]:
        ax1.annotate(f'{y:.3f}', xy=(x, y), xytext=(x, y+0.02), ha='center',
                     fontsize=10, fontweight='bold',
                     bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))

# (b) Drop bar chart
ax2 = plt.subplot(2, 2, 2)
drops = [(baseline_li - light_intensity_results[x]) * 100 for x in bx]
bar_col = ['red' if d > 0 else 'seagreen' for d in drops]
bars2 = ax2.bar(bx, drops, color=bar_col, alpha=0.7, edgecolor='black', width=15)
ax2.axhline(y=0, color='black', linewidth=1)
ax2.set_xlabel('Brightness Change (%)', fontsize=13, fontweight='bold')
ax2.set_ylabel('Accuracy Drop (%)', fontsize=13, fontweight='bold')
ax2.set_title('(b) Accuracy Drop vs Brightness Change', fontsize=14, fontweight='bold')
ax2.grid(True, axis='y', alpha=0.3, linestyle='--')
for bar, d in zip(bars2, drops):
    h = bar.get_height()
    va = 'bottom' if h >= 0 else 'top'
    ax2.text(bar.get_x() + bar.get_width()/2., h + (0.2 if h>=0 else -0.2),
             f'{h:.1f}%', ha='center', va=va, fontsize=9, fontweight='bold')

# (c) Robustness zone distribution
ax3 = plt.subplot(2, 2, 3)
zones = {'Robust (>95%)': [], 'Good (90-95%)': [], 'Fair (85-90%)': [], 'Poor (<85%)': []}
for ch, acc in light_intensity_results.items():
    if acc >= 0.95:   zones['Robust (>95%)'].append(ch)
    elif acc >= 0.90: zones['Good (90-95%)'].append(ch)
    elif acc >= 0.85: zones['Fair (85-90%)'].append(ch)
    else:             zones['Poor (<85%)'].append(ch)
znames  = list(zones.keys())
zcounts = [len(zones[n]) for n in znames]
zcolors = ['#2ECC71', '#3498DB', '#F39C12', '#E74C3C']
bars3 = ax3.barh(znames, zcounts, color=zcolors, alpha=0.8, edgecolor='black')
ax3.set_xlabel('Number of Test Points', fontsize=12, fontweight='bold')
ax3.set_title('(c) Robustness Zone Distribution', fontsize=14, fontweight='bold')
ax3.grid(True, axis='x', alpha=0.3)
for bar in bars3:
    w = bar.get_width()
    ax3.text(w + 0.05, bar.get_y() + bar.get_height()/2.,
             str(int(w)), va='center', fontsize=11, fontweight='bold')

# (d) Extreme conditions
ax4 = plt.subplot(2, 2, 4)
enames  = list(extreme_results.keys())
eaccs   = [extreme_results[n]['accuracy']          for n in enames]
echgs   = [extreme_results[n]['brightness_change'] for n in enames]
ecols   = ['#8B0000' if c < 0 else '#FFD700' for c in echgs]
bars4   = ax4.bar(enames, eaccs, color=ecols, alpha=0.7, edgecolor='black')
ax4.axhline(y=baseline_li, color='green', linestyle='--', linewidth=2,
            alpha=0.6, label='Baseline')
ax4.set_ylabel('Test Accuracy', fontsize=12, fontweight='bold')
ax4.set_title('(d) Extreme Lighting Conditions', fontsize=14, fontweight='bold')
ax4.set_ylim([0, 1.1]); ax4.grid(True, axis='y', alpha=0.3); ax4.legend()
ax4.tick_params(axis='x', rotation=15)
for bar, ch in zip(bars4, echgs):
    h = bar.get_height()
    ax4.text(bar.get_x() + bar.get_width()/2., h + 0.02,
             f'{h:.3f}\n({ch:+d}%)', ha='center', va='bottom',
             fontsize=9, fontweight='bold')

plt.suptitle('Light Intensity Variation Test Results', fontsize=16, fontweight='bold', y=0.995)
plt.tight_layout()
plt.savefig('light_intensity_results.pdf', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: light_intensity_results.png")

print(f"\nBaseline: {baseline_li*100:.2f}%")
best_ch  = max(light_intensity_results, key=light_intensity_results.get)
worst_ch = min(light_intensity_results, key=light_intensity_results.get)
print(f"Best  brightness: {best_ch:+d}%  →  {light_intensity_results[best_ch]*100:.2f}%")
print(f"Worst brightness: {worst_ch:+d}%  →  {light_intensity_results[worst_ch]*100:.2f}%")
print(f"Total range: {(max(light_intensity_results.values())-min(light_intensity_results.values()))*100:.2f}%")
for zn, bl in zones.items():
    if bl: print(f"  {zn}: {bl}")